version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    container_name: api
    volumes:
    - ./.env:/opt/app/.env
    networks:
    - myNetwork
  rmq:
    image: rabbitmq:3-management
    restart: always
    networks:
    - myNetwork
    environment:
    - RABBITMQ_DEFFAULT_USER=admin
    - RABBITMQ_DEFFAULT_PASS=admin

networks:
  myNetwork:
    driver: bridge
